# Lecture 3 - CS677 - Pandas Overview 
## Data Science Numerics
Faculty: Farshid Alizadeh-Shabdiz


### Data Processing

In [1]:
import numpy as np

In [2]:
x_points = np.arange(-2, 3, 1)
y_points = np.arange(-1, 2, 1)
print(x_points)
print(y_points)

[-2 -1  0  1  2]
[-1  0  1]


In [3]:
xs, ys = np.meshgrid(x_points, y_points)


In [4]:
print(xs)

[[-2 -1  0  1  2]
 [-2 -1  0  1  2]
 [-2 -1  0  1  2]]


In [5]:
print(ys)

[[-1 -1 -1 -1 -1]
 [ 0  0  0  0  0]
 [ 1  1  1  1  1]]


In [6]:
# evaluate f(x) =sqrt(x^2 + y^2 )
z = np.round(np.sqrt(xs**2 + ys**2), 2)
print(z)

[[2.24 1.41 1.   1.41 2.24]
 [2.   1.   0.   1.   2.  ]
 [2.24 1.41 1.   1.41 2.24]]


# Pandas
- Panel Data Module
- Main objects 
    - Series: like a column of a table
    - Dataframes: similar to a table
- Designed to manage indexed data, same as SQL

## install via pip
pip install pandas
- Then import Numpy and Pandas, both

In [7]:
import numpy as np
import pandas as pd

### Pandas Series Object
- similar to an Excel column 
- ”similar” to dictionary:
    1. key: column name
    2.value: list of values (all of the same type)
- but values could have own index
#### Example:
- Weight = [100, 150, 130, 150, 180, 190, 170, 165]
- weight is the key
- each list item gets indexed


In [8]:
index = [ "x1","x2","x3","x4", "x5","x6","x7","x8"]

In [9]:
weight = [100, 150, 130, 150, 180, 190, 170, 165]

In [10]:
weight_series =pd.Series(weight, index)
print(weight_series)

x1    100
x2    150
x3    130
x4    150
x5    180
x6    190
x7    170
x8    165
dtype: int64


In [11]:
# Create a series from a dictionary
new_dict = {"x1":100,"x2":150,"x3":130,"x4":150, "x5":180,"x6":190,"x7":170,"x8":165}
weight_series = pd.Series(new_dict)
weight_series

x1    100
x2    150
x3    130
x4    150
x5    180
x6    190
x7    170
x8    165
dtype: int64

In [12]:
weight_series['x4'] , weight_series["x1"] 

(150, 100)

In [13]:
# Operation on series
index = [ "x1","x2","x3","x4", "x5","x6","x7","x8"]
Weight = [100, 150, 130, 150, 180, 190, 170, 165]
Foot = [6,8,7,9,13,11,12,10]

weight_series = pd.Series(Weight , index)
foot_series = pd.Series(Foot, index) 

weight_per_foot=weight_series/foot_series
weight_per_foot

x1    16.666667
x2    18.750000
x3    18.571429
x4    16.666667
x5    13.846154
x6    17.272727
x7    14.166667
x8    16.500000
dtype: float64

In [14]:
# Broadcasting - element wise broadcasting
weight_series * 2

x1    200
x2    300
x3    260
x4    300
x5    360
x6    380
x7    340
x8    330
dtype: int64

## Pandas Dataframe
- series contains a list with index
- dataframe is a collection of series with (same) index
- Can create in many ways:
    1. series object
    2. reading csv/Excel file 
    3. numpy array
    4. dictionary

In [15]:
df = pd.DataFrame(
     {
     "Weight": [100, 150, 130, 150, 180, 190, 170, 165], 
     "Foot" : [6,8,7,9,13,11,12,10]
     }
    )
df

Weight  Foot
0     100     6
1     150     8
2     130     7
3     150     9
4     180    13
5     190    11
6     170    12
7     165    10

In [16]:
# Custom Indexing
df = pd.DataFrame(
    {
     "Weight": [100, 150, 130, 150, 180, 190, 170, 165], 
     "Foot" : [6,8,7,9,13,11,12,10]
    },
    index=["x1","x2","x3","x4", "x5","x6","x7","x8"])
df

Weight  Foot
x1     100     6
x2     150     8
x3     130     7
x4     150     9
x5     180    13
x6     190    11
x7     170    12
x8     165    10

In [17]:
# Getting column value
df["Foot"]

x1     6
x2     8
x3     7
x4     9
x5    13
x6    11
x7    12
x8    10
Name: Foot, dtype: int64

In [18]:
# Multiple columns
print(df[ ["Foot", "Weight"] ])
print(df[ ['Foot', 'Weight'] ])

    Foot  Weight
x1     6     100
x2     8     150
x3     7     130
x4     9     150
x5    13     180
x6    11     190
x7    12     170
x8    10     165
    Foot  Weight
x1     6     100
x2     8     150
x3     7     130
x4     9     150
x5    13     180
x6    11     190
x7    12     170
x8    10     165


In [19]:
# Creating a New Column
# vectorized computation
df["weight_per_foot"] = df["Weight"]/df["Foot"]
df

Weight  Foot  weight_per_foot
x1     100     6        16.666667
x2     150     8        18.750000
x3     130     7        18.571429
x4     150     9        16.666667
x5     180    13        13.846154
x6     190    11        17.272727
x7     170    12        14.166667
x8     165    10        16.500000

In [20]:
# Renaming Column(s)
df.rename(columns={"weight_per_foot":"density"}, inplace = True)
df

Weight  Foot    density
x1     100     6  16.666667
x2     150     8  18.750000
x3     130     7  18.571429
x4     150     9  16.666667
x5     180    13  13.846154
x6     190    11  17.272727
x7     170    12  14.166667
x8     165    10  16.500000

In [21]:
# Dropping Column(s)
df.drop("density", axis=1,inplace=True)
df

Weight  Foot
x1     100     6
x2     150     8
x3     130     7
x4     150     9
x5     180    13
x6     190    11
x7     170    12
x8     165    10

In [22]:
# Simple Sorting
# - sorting by one column 
df_2 = df.sort_values(by=["Weight"], ascending = [False])
df_2

Weight  Foot
x6     190    11
x5     180    13
x7     170    12
x8     165    10
x2     150     8
x4     150     9
x3     130     7
x1     100     6

In [23]:
# Multi-Column Sorting
# - sorting by multiple columns • can be done ”in-place”
df_3 = df.sort_values(
          by=["Weight","Foot"],
          ascending=[False, False])
df_3

Weight  Foot
x6     190    11
x5     180    13
x7     170    12
x8     165    10
x4     150     9
x2     150     8
x3     130     7
x1     100     6

In [24]:
# head() and tail()
# - head(n) - first n rows
# - tail(n) - last n rows
print(df.head(2))
print(df.tail())

    Weight  Foot
x1     100     6
x2     150     8
    Weight  Foot
x4     150     9
x5     180    13
x6     190    11
x7     170    12
x8     165    10


In [25]:
# Code for the Dataset
data = pd.DataFrame(
{ "id":[ 1,2,3,4,5,6,7,8],
  "Label":["green","green","green","green","red","red","red","red"], 
  "Height":[5,5.5,5.33,5.75,6.00,5.92,5.58,5.92],
  "Weight":[100,150,130,150,180,190,170,165], 
  "Foot":[6, 8, 7, 9, 13, 11, 12, 10]}
    , columns=["id","Height","Weight","Foot","Label"]
                    )
data

id  Height  Weight  Foot  Label
0   1    5.00     100     6  green
1   2    5.50     150     8  green
2   3    5.33     130     7  green
3   4    5.75     150     9  green
4   5    6.00     180    13    red
5   6    5.92     190    11    red
6   7    5.58     170    12    red
7   8    5.92     165    10    red

In [26]:
# Alternative Approach
data = pd.DataFrame(
    data = [
            [1, 5,100, 6, "green"], 
            [2, 5.5,  150, 8, "green"],
            [3, 5.33, 130, 7, "green"],
            [4, 5.75, 150, 9, "green"], 
            [5, 6,    180, 13, "red"], 
            [6, 5.92, 190, 11, "red"], 
            [7, 5.58, 170, 12, "red"],
            [8, 5.92, 165, 10, "red"]
           ],
columns = ["id","Height","Weight", "Foot","Label"] )
data  

id  Height  Weight  Foot  Label
0   1    5.00     100     6  green
1   2    5.50     150     8  green
2   3    5.33     130     7  green
3   4    5.75     150     9  green
4   5    6.00     180    13    red
5   6    5.92     190    11    red
6   7    5.58     170    12    red
7   8    5.92     165    10    red

In [27]:
data.index

RangeIndex(start=0, stop=8, step=1)

In [28]:
data.columns

Index(['id', 'Height', 'Weight', 'Foot', 'Label'], dtype='object')

In [29]:
#selection via index: 
# 1. .loc by label
# 2. .iloc by position
data.iloc[5]

id           6
Height    5.92
Weight     190
Foot        11
Label      red
Name: 5, dtype: object

In [30]:
# selection of multiple indices
print(data.iloc[[5,7]])

   id  Height  Weight  Foot Label
5   6    5.92     190    11   red
7   8    5.92     165    10   red


In [31]:
# se;ection via index object
data.iloc[data.index[1:7:2]]

id  Height  Weight  Foot  Label
1   2    5.50     150     8  green
3   4    5.75     150     9  green
5   6    5.92     190    11    red

In [32]:
# Statistical Functions
data[['Height','Weight','Foot']].mean()

Height      5.625
Weight    154.375
Foot        9.500
dtype: float64

In [33]:
# Lambda Functions
#   - apply lambda functions
data[['Height','Weight']].apply(lambda x: x**2)

Height  Weight
0  25.0000   10000
1  30.2500   22500
2  28.4089   16900
3  33.0625   22500
4  36.0000   32400
5  35.0464   36100
6  31.1364   28900
7  35.0464   27225

In [34]:
# Adding a Column(s)
data['n_col']=['a','b','c','d','e','f','g','h']
data

id  Height  Weight  Foot  Label n_col
0   1    5.00     100     6  green     a
1   2    5.50     150     8  green     b
2   3    5.33     130     7  green     c
3   4    5.75     150     9  green     d
4   5    6.00     180    13    red     e
5   6    5.92     190    11    red     f
6   7    5.58     170    12    red     g
7   8    5.92     165    10    red     h

In [35]:
#Dropping Column or row
#  - axis: 1-columns, 0 - rows
data.drop(['n_col'],axis=1,inplace=True)
data

id  Height  Weight  Foot  Label
0   1    5.00     100     6  green
1   2    5.50     150     8  green
2   3    5.33     130     7  green
3   4    5.75     150     9  green
4   5    6.00     180    13    red
5   6    5.92     190    11    red
6   7    5.58     170    12    red
7   8    5.92     165    10    red

## Data Wrangling

In [36]:
# Dropping Duplicates
#  - can also drop ”in-place”
data_2 = data.drop_duplicates("Weight")
data_2

id  Height  Weight  Foot  Label
0   1    5.00     100     6  green
1   2    5.50     150     8  green
2   3    5.33     130     7  green
4   5    6.00     180    13    red
5   6    5.92     190    11    red
6   7    5.58     170    12    red
7   8    5.92     165    10    red

In [37]:
# Desribing the Dataset
data.describe()

id    Height      Weight      Foot
count  8.00000  8.000000    8.000000   8.00000
mean   4.50000  5.625000  154.375000   9.50000
std    2.44949  0.343428   28.962722   2.44949
min    1.00000  5.000000  100.000000   6.00000
25%    2.75000  5.457500  145.000000   7.75000
50%    4.50000  5.665000  157.500000   9.50000
75%    6.25000  5.920000  172.500000  11.25000
max    8.00000  6.000000  190.000000  13.00000

In [38]:
# Reversing Rows (similar to lists)
data_rev_rows = data.loc[::-1]
data_rev_rows

id  Height  Weight  Foot  Label
7   8    5.92     165    10    red
6   7    5.58     170    12    red
5   6    5.92     190    11    red
4   5    6.00     180    13    red
3   4    5.75     150     9  green
2   3    5.33     130     7  green
1   2    5.50     150     8  green
0   1    5.00     100     6  green

In [39]:
# Reversing Columns
data_rev_cols = data.loc[:, ::-1]
data_rev_cols

Label  Foot  Weight  Height  id
0  green     6     100    5.00   1
1  green     8     150    5.50   2
2  green     7     130    5.33   3
3  green     9     150    5.75   4
4    red    13     180    6.00   5
5    red    11     190    5.92   6
6    red    12     170    5.58   7
7    red    10     165    5.92   8

In [40]:
# Filtering s DataFrame
data_red = data[ data["Label"]=="red" ]
data_red

id  Height  Weight  Foot Label
4   5    6.00     180    13   red
5   6    5.92     190    11   red
6   7    5.58     170    12   red
7   8    5.92     165    10   red

In [41]:
data_s = data[data["Foot"].isin([7,9])] # return values which "is in" the provided list
data_s

id  Height  Weight  Foot  Label
2   3    5.33     130     7  green
3   4    5.75     150     9  green

In [42]:
# Filtering s DataFrame with multiple criteria
data_med = data[
                (data["Foot"] > 6) & (data["Weight"] < 160)
               ]
data_med

id  Height  Weight  Foot  Label
1   2    5.50     150     8  green
2   3    5.33     130     7  green
3   4    5.75     150     9  green

In [43]:
# Counting Values
counts = data['Weight'].value_counts()
counts

150    2
190    1
170    1
165    1
180    1
130    1
100    1
Name: Weight, dtype: int64

In [44]:
print(data)

   id  Height  Weight  Foot  Label
0   1    5.00     100     6  green
1   2    5.50     150     8  green
2   3    5.33     130     7  green
3   4    5.75     150     9  green
4   5    6.00     180    13    red
5   6    5.92     190    11    red
6   7    5.58     170    12    red
7   8    5.92     165    10    red


In [45]:
# Aggregating
data_m = data.groupby("Label").agg('mean')
print(data_m)

data_m = data.groupby("Label").agg('min', 'max')
print(data_m)

        id  Height  Weight  Foot
Label                           
green  2.5   5.395  132.50   7.5
red    6.5   5.855  176.25  11.5
       id  Height  Weight  Foot
Label                          
green   1    5.00     100     6
red     5    5.58     165    10


In [46]:
data_ms = data.groupby("Label") ["Weight"].agg(["mean","std"])
print(data_ms)

         mean        std
Label                   
green  132.50  23.629078
red    176.25  11.086779


In [47]:
df = pd.DataFrame([[1, 2, 3],
...                    [4, 5, 6],
...                    [7, 8, 9],
...                    [np.nan, np.nan, np.nan]],
...                   columns=['A', 'B', 'C'])
df.agg(['sum', 'min'])

A     B     C
sum  12.0  15.0  18.0
min   1.0   2.0   3.0

In [48]:
df.agg("mean", axis="columns")

0    2.0
1    5.0
2    8.0
3    NaN
dtype: float64

# Creating a Data Mesh

In [49]:
data = pd.DataFrame(
            {'id': [ 1,2,3,4,5,6,7,8],
            'Label': ['green','green','green','green','red','red','red','red'], 
            'Height': [5, 5.5, 5.33, 5.75,6.00 , 5.92 , 5.58 , 5.92] , 
            'Weight': [100, 150, 130, 150,180, 190, 170, 165], 
            'Foot': [6, 8, 7, 9, 13, 11, 12, 10]},
columns = ['id', 'Height', 'Weight', 'Foot', 'Label'] )

In [50]:
data

id  Height  Weight  Foot  Label
0   1    5.00     100     6  green
1   2    5.50     150     8  green
2   3    5.33     130     7  green
3   4    5.75     150     9  green
4   5    6.00     180    13    red
5   6    5.92     190    11    red
6   7    5.58     170    12    red
7   8    5.92     165    10    red

In [51]:
height = np.array([5,5.5,5.33,5.75,6,5.92,5.58,5.92])
weight = np.array([6,8,7,9,13,11,12,10])


In [52]:
correlation = np.corrcoef(height,weight)
correlation

array([[1.        , 0.82193197],
       [0.82193197, 1.        ]])

In [53]:
correlation = np.corrcoef(height,weight)[0,1]
correlation

0.8219319721553828